config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users
	root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.build(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :developer, :genre, :rating)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:" %>
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :developer %>
    <br>
    <%= f.text_field :developer %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :rating %>
    <br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class='container'>
  <div class='jumbotron'>
<h1>Editing game</h1>
<%= render 'form' %>
<%= link_to 'View', @game %>
|
<%= link_to 'Back to List', games_path %>
</div>
</div>

app/views/games/index.html.erb
<div class='container'>
  <div class='jumbotron'>
<h1>Your Game List </h1>
<table style="border-spacing: 15px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Developer</th>
      <th>Genre</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <% if game.user_id == current_user.id %>
      <tr>
        <td>
          <%= game.name %>
        </td>
        <td>
          <%= game.developer %>
        </td>
        <td>
          <%= game.genre %>
        </td>
        <td>
          <%= game.rating %>
        </td>
        <td>
          <%= link_to 'View', game %>
        </td>
        <td>
          <%= link_to 'Edit', edit_game_path(game) %>
        </td>
        <td>
          <%= link_to 'Remove', game, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>


    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Game', new_game_path %>
</div>
</div>

app/views/games/new.html.erb
<div class='container'>
  <div class='jumbotron'>
    <h1>New game</h1>
    <%= render 'form' %>
    <%= link_to 'Back to List', games_path %>
  </div>
</div>

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.erb
<div class='container'>
  <div class='jumbotron'>
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Name:</b>
  <%= @game.name %>
</p>
<p>
  <b>Developer:</b>
  <%= @game.developer %>
</p>
<p>
  <b>Genre:</b>
  <%= @game.genre %>
</p>
<p>
  <b>Rating:</b>
  <%= @game.rating %>
</p>
<%= link_to 'Edit Game', edit_game_path(@game) %>
|
<%= link_to 'Back to List', games_path %>
</div>
</div>

app/views/home/contact.html.erb
<div class="container">
  <div class="jumbotron">
<h1>
  <center><%= t('.title') %></center>
</h1>
<p>
  <%= t('.contact_us') %>
</p>
<%= form_tag request_contact_path, method: 'post' do %>
  <%= label_tag :name, t('.name') %>
  <br>
  <%= text_field_tag :name, '',title:t('enter_name'), size:50 %>
    <br>
  <%= label_tag :email, t('.email') %>
  <br>
  <%= email_field_tag :email, '', title: t('.enter_email') %>
  <br>
  <%= label_tag :telephone, t('.telephone') %>
  <br>
  <%= text_field_tag :telephone, '', title: t('.enter_telephone') %>
  <br>
  <%= label_tag :message, t('.message') %>
  <br>
  <%= text_field_tag :message, '', title: t('.message'), size: 100 %>
  <br>  <br>
  <%= submit_tag t('.submit') %>
<% end %>
</div>
</div>

app/views/home/home.html.erb
<div class="container">
  <div class="jumbotron vertical-center">
    <body>
    <background-color :grey>
    </body>
  <h1>
     <center>PlayBot</center>
  </h1>
  <h3>
    <center>Find and track games and TV shows that you are interested in!</center>
  </h3>
</div>
</div>

app/views/layouts/_footer.html.erb
<div id="push"> </div>
<footer class="foot navbar-fixed-bottom"
  <div class="container">
    <nav>
      <ul>
        <p>
          <li> <%= link_to "Contact us", contact_path, class: "active" %></li>
        </p>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"> Toggle Nav</span>
        <span class="icon-bar"</span>
        <span class="icon-bar"</span>
        <span class="icon-bar"</span>
      </button>
      <%= link_to "Homepage", root_path, class: "navbar-brand" %>
   </div>

   <div class="collapse navbar-collapse" id="bs-examplee-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li> <%= link_to "Your List", games_path, class: "active" %></li>
          <li> <%= link_to "Enter a Game Manually", new_game_path, class: "active" %></li>
      </ul>

      <% if user_signed_in? %>
      <ul class="nav navbar-right">
          <li> <%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      </ul>

      <% else %>
      <ul class="nav navbar-right">
         <li> <%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
       </ul>

      <ul class="nav navbar-right">
          <li> <%= link_to "Sign In", new_user_session_path, class: "active" %></li>
      </ul>

      <% end %>


    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Enter</button>
    </form>

  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="ie=edge" http-equiv="x-ua-compatible"/>
    <title>
      <%= t('app_title') %>
    </title>
    <meta content="<%= t('app_description') %>" name="description"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'modernizr' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>
    <%= render 'layouts/footer' %>
    <%= yield %>


  </body>
</html>